# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration

require 'capybara/rspec'
require 'selenium-webdriver'
require 'selenium'
require 'capybara-screenshot/rspec'


client = Selenium::WebDriver::Remote::Http::Default.new


$client_backup = Selenium::WebDriver::Remote::Http::Default.new


browser = ENV['BROWSER_TYPE']

if browser == nil || browser == ""
  browser = 'firefox'
end

if browser == 'firefox'

	Capybara.register_driver :mainDriver do |app|
		Capybara::Selenium::Driver.new(app, :browser => :firefox, :profile => $profile, :http_client =>client)#
  end

elsif browser == 'chrome'

	Capybara.register_driver :mainDriver do |app|
  	Capybara::Selenium::Driver.new(app, :browser => :chrome, :http_client =>client)
	end

elsif browser == 'ie'

  capabilities = Selenium::WebDriver::Remote::Capabilities.new
  capabilities[:ignoreProtectedModeSettings] = true
  capabilities[:javascriptEnabled] = true
  capabilities[:cssSelectorsEnabled] = true
  capabilities[:acceptSslCerts] = true

  Capybara.register_driver :mainDriver do |app|
    Capybara::Selenium::Driver.new(app, :browser => :internet_explorer, 
                                        :desired_capabilities => capabilities, :http_client =>client)
  end


end
Capybara.default_driver = :mainDriver

Capybara.session_name = "main"

Capybara::Screenshot.register_driver(:mainDriver) do |driver, path|
  driver.browser.save_screenshot(path)
end

Capybara.run_server = false

Capybara.default_selector = :xpath

Capybara::Screenshot.register_filename_prefix_formatter(:rspec) do |example|
  "screenshot_#{example.description.gsub(' ', '-').gsub(/^.*\/spec\//, '')}"
end

begin
	Capybara.save_path = "./screenshot/" + Time.now.inspect.split('+')[0].gsub(/\s/,'').gsub(/:/,'') + "/"
rescue
	Capybara.save_and_open_page_path = "./screenshot/" + Time.now.inspect.split('+')[0].gsub(/\s/,'').gsub(/:/,'') + "/"

end
Capybara::Screenshot.autosave_on_failure = false

RSpec.configure do |config|
  config.run_all_when_everything_filtered = true
end
